### ISSUE TITLE
Precompiled versions - Zip Files Corrupted

### ISSUE THREAD

**Issue by abbysdad** [DIYOSEPP/oseppBlock#6]
I seem to have an issue with the precompiled versions.  When I download the zip files I get a very small zip file that is corrupted.  I looked at the contents and it is not what I would expect.  
Example: oseppBlock-win32-x64.zip
Contents(used ultra edit to look at the corrupted zip file):
version https://git-lfs.github.com/spec/v1
oid sha256:d0b0ac10db9bc3963b023b2b9b575b2d7e3a4bcf170d1f2bab748f287c67efe0
size 110616382

I tried cloning the master and the zip files were all corrupted similarly.   
The raw download resulted in the same outcome as well.  I use GitHub infrequently and am not sure where to go from here.  Any help would be appreciated.

**Comment by zhsvector** [comment]
Thank you for your feedback, We have moved the precompiled files to the release page, 
please visit url https://github.com/DIYOSEPP/oseppBlock/releases

**Comment by abbysdad** [comment]
Thank you very much.  My daughter is chomping at the bit to work through the STEM KIT 1 workbook!
